### PR TITLE
Add autotracking dungeon reward information

### PR DESCRIPTION
**Pull request by Patlukat**
this only works after commit [600a78fd](https://github.com/TestRunnerSRL/OoT-Randomizer/commit/600a78fd0759a75f01c1f2829e77600de90b09ea), version 6.2.5

OoT-Randomizer/ASM/src/config.asm dictates which settings will be preserved to read at a later time, for example by autotrackers, as per test I did. 

There is a speciific part added with v6.2.5 called AUTO_TRACKER_CONTEXT, which gives autotrackers information about the dungeons settings and rewards.

But everything defined in config.asm can be used for autotracker support.

### CODE REVIEW

**Comment by coavins** [comment]
This is very cool, good work! I had no idea this was possible. Do you know if the auto tracker context contains spoilers for information the player couldn't have learned in-game yet? Or does it only populate once the player has seen this for the first time?

**Comment by Patlukat** [comment]
It sadly contains spoilers for information the player couldn't have learned in-game yet. The Dungeon Reward Info here is used to only check the correct medallion once the medallion is actually received, but from the start of the autotracking the medallions and associated dungeons are known in the backend.
This can lead to problems e.g. random settings. You would be able to know from the start of autotracking what changed to what, so you have to be careful what is known in the backend and what is actually shown.


fenhl for example checks if the player is looking at the dungeon info screen in the pause menu and updates the tracker accordingly.
https://github.com/fenhl/oottracker/blob/main/crate/oottracker/src/lib.rs
```rust
// read dungeon reward info if the player is looking at the dungeon info screen in the pause menu
if self.tracker_ctx.cfg_dungeon_info_enable && self.ram.pause_state == 6 && self.ram.pause_screen_idx == 0 && !self.ram.pause_changing && self.ram.input_p1_raw_pad.contains(Pad::A) && self.tracker_ctx.cfg_dungeon_info_reward_enable {
            for (dungeon, reward) in &self.tracker_ctx.cfg_dungeon_rewards {
                let mut known = true;
                if self.tracker_ctx.cfg_dungeon_info_reward_need_altar {
                    known &= match reward {
                        DungeonReward::Medallion(_) => self.ram.save.inf_table.55.contains(InfTable55::TOT_ALTAR_READ_MEDALLION_LOCATIONS),
                        DungeonReward::Stone(_) => self.ram.save.inf_table.55.contains(InfTable55::TOT_ALTAR_READ_STONE_LOCATIONS),
                    };
                }
```

I went with a primitive approach and just saved it in backend to correctly set which medallion goes with which dungeon once the dungeon reward updates.

**Comment by Patlukat** [comment]
Also a good example is RAINBOW_BRIDGE_CONDITION which can be read from the beginning but i think can only be known in-game through the adult ToT altar and only if Misc. Hints in the Other section is activated.

**Comment by coavins** [comment]
I made some tweaks to look up the address of the autotracker context at runtime according to the comments on [this page](https://github.com/OoTRandomizer/OoT-Randomizer/blob/Dev/Notes/auto-tracker-ctx.md). When the address is found, it will be stored in `ADDR_AUTOTRACKER_CONTEXT` and a new memory watch will be created for that whole region of memory.

I'm not sure which version of the context you were targeting at the time of this PR, but I used the `CFG_DUNGEON_REWARDS` offset of `0x20` for version 4 which is the latest at time of writing.

I also added an `updateFromAutotrackerContext` function which calls your `updateMedalList`. This is closer in design to the other `updateXfromY` functions that the memory watches are using. We should be able to add more autotracker context stuff here in the future.

`updateMedalList` seems to be working (at least the free medal is correct). I hope I can find some time to do a test run sometime to prove out your changes to `updateDungeonPrizeFromDataAndFlags`. If this is working, then I think the PR will be ready to merge.

PS: I also retargeted this PR to the master branch, and merged its changes. The `autotracker` branch I was using before is just too much overhead. We can figure it out later if we ever merge to the upstream.

**Pull request merged**
